1.20.1
PrismarineJS/minecraft-data-generator-server pull request #5
Opened 2023-08-20 13:22 UTC by MathiasElgaard

Updated for 1.20.1

Substituted block materials with `BlockTags`, since `Material` was removed in Minecraft 1.20. Details: https://fabricmc.net/2023/05/25/120.html

2023-08-20 13:43 UTC, rom1504 commented
Cool, are you using it to update mcdata ?

2023-08-20 13:53 UTC, MathiasElgaard commented
@rom1504 Yes, I'm using it to update mcData, and in doing so I get data that fixes this issue: https://github.com/PrismarineJS/minecraft-data/issues/757

2023-08-25 20:59 UTC, rom1504 commented
ok please open a pr on mcdata

2023-08-25 21:03 UTC, u9g requested changes

2023-08-25 21:03 UTC, u9g commented on src/main/java/dev/u9g/minecraftdatagenerator/generators/MaterialsDataGenerator.java
> +        // resultList.add(new MaterialInfo("gourd", blockState -> blockState.getMaterial() == Material.GOURD));
Please don't leave commented out code in the repo.

2023-08-27 10:29 UTC, MathiasElgaard commented
I removed the commented out code

2023-09-04 09:53 UTC, merged